### ISSUE TITLE
Feature request: option to pass through `GRPC.Stub.connect/2` options when creating Authzed Client

### ISSUE THREAD

**Issue by pwcsquared** [goodhamgupta/authzed_ex#24]
There are several options that are supported when calling `GRPC.Stub.connect` that would be very nice to have access to when calling `Authzed.Api.V1.Client.new/2` and `new/3`:

https://hexdocs.pm/grpc/GRPC.Stub.html#connect/2-options

**Comment by pwcsquared** [comment]
I'm happy to open a PR that does this!

**Comment by goodhamgupta** [comment]
Marking this as closed now. Thanks @pwcsquared!
